apiVersion: v1
kind: Pod
metadata:
  name: cosmos-reason2-inference
  namespace: runai-embodied-ai
spec:
  restartPolicy: Never
  containers:
    - name: cosmos-reason2-inference
      image: default-route-openshift-image-registry.apps.octocp.alexnet.htx/runai-embodied-ai/cosmos-reason2:latest
      command:
        - /workspace/docker/entrypoint.sh
      args:
        - sleep 
        - infinity 
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        - name: HF_HUB_OFFLINE
          value: "1"
        - name: PATH
          value: /opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: PIP_INDEX_URL
          value: file:///root/P1a/python/web/simple
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        limits:
          nvidia.com/gpu: "1"
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: object-data
          mountPath: /root/P1a
          readOnly: true
        - name: persistent-data
          mountPath: /persistent-data
        - name: rclone-config
          mountPath: /root/.config/rclone/rclone.conf
          subPath: rclone.conf
        - name: mc-home
          mountPath: /root/.mc
        - name: mc-config
          mountPath: /root/.mc/config.json
          subPath: mc.conf
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: rclone-config
      secret:
        secretName: rclone-config
    - name: mc-home
      emptyDir: {}
    - name: mc-config
      secret:
        secretName: mc-config
        defaultMode: 0444
    - name: object-data
      persistentVolumeClaim:
        claimName: hot-storage-data-pvc
    - name: persistent-data
      persistentVolumeClaim:
        claimName: jupyter-5-persistent-hot-storage-pvc
    - name: dshm
      emptyDir:
        medium: Memory
